openapi: 3.0.0
info:
  title: 3gpp-bdt
  version: "v1"
externalDocs:
  description: Documentation
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.122/'
servers:
  - url: https://{apiRoot}/3gpp-bdt/v1
    variables:
      apiRoot:
        default: demohost.com
        description: apiRoot as defined in subclause subclause 5.2.4 of 3GPP TS 29.122, excluding the https:// part.
paths:
  /{scsAsId}/subscriptions:
    get:
      parameters:
        - name: scsAsId
          description: String identifying the SCS/AS.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: all BDT policy subscriptions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bdt'
                minItems: 0
                description: individual BDT policy subscription.
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29122_CommonData.yaml#/components/schemas/ProblemDetails'
    post:
      parameters:
        - name: scsAsId
          description: String identifying the SCS/AS.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Contains the data to create a BDT subscription.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bdt'
      responses:
        '201':
          description: Background data transfer policies offered to the SCS/AS.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bdt'
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29122_CommonData.yaml#/components/schemas/ProblemDetails'
  /{scsAsId}/subscriptions/{subscriptionId}:
    get:
      parameters:
        - name: scsAsId
          description: String identifying the SCS/AS.
          in: path
          required: true
          schema:
            type: string
        - name: subscriptionId
          description: String identifying the individual BDT policy resource in the SCEF.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Background data transfer policies offered to and selected by the SCEF.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bdt'
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29122_CommonData.yaml#/components/schemas/ProblemDetails'
    patch:
      parameters:
        - name: scsAsId
          description: String identifying the SCS/AS.
          in: path
          required: true
          schema:
            type: string
        - name: subscriptionId
          description: String identifying the individual BDT policy resource in the SCEF.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Contains information to be performed on the Bdt data structure to select a transfer policy.
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/BdtPatch'
      responses:
        '200':
          description: The Individual BDT Policy resource is modified with a selected policy and a representation of that resource is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bdt'
        '204':
          description: The Individual BDT Policy resource is modified with a selected policy.
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29122_CommonData.yaml#/components/schemas/ProblemDetails'
    delete:
      parameters:
        - name: scsAsId
          description: String identifying the SCS/AS.
          in: path
          required: true
          schema:
            type: string
        - name: subscriptionId
          description: String identifying the individual BDT policy resource in the SCEF.
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The Individual BDT Policy resource is deleted.
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29122_CommonData.yaml#/components/schemas/ProblemDetails'
components:
  schemas: 
    Bdt:
      type: object
      properties:
        self:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Link'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        volumePerUE:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/UsageThreshold'
        numberOfUEs:
          type: integer
          description: Identifies the number of UEs.
        desiredTimeWindow:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/TimeWindow'
        locationArea:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/LocationArea'
        referenceId:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/BdtReferenceId'
        transferPolicies:
          type: array
          items:
            $ref: '#/components/schemas/TransferPolicy'
          minItems: 0
          description: Identifies an offered transfer policy.
          readOnly: true
        selectedPolicy:
          type: integer
          description: Identity of the selected background data transfer policy. Shall not be present in initial message exchange, can be provided by NF service consumer in a subsequent message exchange.
      required:
        - supportedFeatures
        - volumePerUE
        - numberOfUEs
        - desiredTimeWindow
    BdtPatch:
      type: object
      properties:
        selectedPolicy:
          type: integer
          description: Identity of the selected background data transfer policy.
      required:
        - selectedPolicy
    TransferPolicy:
      type: object
      properties:
        bdtPolicyId:
          type: integer
          description: Identifier for the transfer policy
        maxUplinkBandwidth:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Bandwidth'
        maxDownlinkBandwidth:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Bandwidth'
        ratingGroup:
          type: integer
          description: Indicates the rating group during the time window.
        timeWindow:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/TimeWindow'
      required:
        - bdtPolicyId
        - ratingGroup
        - timeWindow
