openapi: 3.0.0
info:
  title: 3gpp-cp-parameter-provisioning
  version: "v1"
externalDocs:
  description: Documentation
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.122/'
servers:
  - url: https://{apiRoot}/3gpp-cp-parameter-provisioning/v1
    variables:
      apiRoot:
        default: demohost.com
        description: apiRoot as defined in subclause subclause 5.2.4 of 3GPP TS 29.122, excluding the https:// part.
paths:
  /{scsAsId}/subscriptions:
    get:
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. The subscription information related to the request URI is returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CpInfo'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    post:
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CpInfo'
          description: Change information in CP parameter set.
      responses:
        '201':
          description: Created. The subscription was created successfully. The SCEF shall return the created subscription in the response payload body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpInfo'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '409':
          $ref: 'TS29122_CommonData.yaml#/components/responses/409'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /{scsAsId}/subscriptions/{subscriptionId}:
    get:
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. The subscription information related to the request URI is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpInfo'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CpInfo'
          description: Change information in CP parameter set(s).
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. The subscription was modified successfully. The SCEF shall return an updated subscription in the response payload body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpInfo'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '409':
          $ref: 'TS29122_CommonData.yaml#/components/responses/409'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content. The subscription was deleted successfully. The payload body shall be empty.
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /{scsAsId}/subscriptions/{subscriptionId}/cpSets/{setId}:
    get:
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
        - name: setId
          in: path
          description: Identifier of the CP parameter set
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. The subscription information related to the request URI is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpParameterSet'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CpParameterSet'
          description: Change information in CP parameter set.
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
        - name: setId
          in: path
          description: Identifier of the CP parameter set
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. The CP parameter set resource was modified successfully. The SCEF shall return an updated CP parameter set resource in the response payload body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpParameterSet'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '409':
          $ref: 'TS29122_CommonData.yaml#/components/responses/409'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      parameters:
        - name: scsAsId
          in: path
          description: Identifier of the SCS/AS as defined in subclause subclause 5.2.4 of 3GPP TS 29.122.
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: path
          description: Subscription ID
          required: true
          schema:
            type: string
        - name: setId
          in: path
          description: Identifier of the CP parameter set
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content. The subscription was deleted successfully. The payload body shall be empty.
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '412':
          $ref: 'TS29122_CommonData.yaml#/components/responses/412'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas: 
    CpInfo:
      type: object
      properties:
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        externalId:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/ExternalId'
        msisdn:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Msisdn'
        externalGroupId:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/ExternalGroupId'
        cpParameterSet:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CpParameterSet'
          minProperties: 1
          description: Identifies a set of CP parameter information that may be part of this CpInfo structure.
      required:
        - supportedFeatures
        - cpParameterSet
    CpParameterSet:
      type: object
      properties:
        setId:
          type: string
          description: SCS/AS-chosen correlator provided by the SCS/AS in the request to create a resource fo CP parameter set(s). 
        self:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Link'
        validityTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTime'
        periodicCommunicationIndicator:
          $ref: '#/components/schemas/CommunicationIndicator'
        communicationDurationTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DurationSec'
        periodicTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DurationSec'
        scheduledCommunicationTime:
          $ref: '#/components/schemas/ScheduledCommunicationTime'
        stationaryIndication:
          $ref: '#/components/schemas/StationaryIndication'
        expectedUmts:
          type: array
          items:
            $ref: ' TS29122_CommonData.yaml#/components/schemas/LocationArea'
          minItems: 0
          description: Identifies the UE's expected geographical movement. The attribute is only applicable in 5G.
      required:
        - setId
    ScheduledCommunicationTime:
      type: object
      properties:
        daysOfWeek:
          type: array
          items:
            $ref: 'TS29122_CommonData.yaml#/components/schemas/DayOfWeek'
          minItems: 0
          maxItems: 6
          description: Identifies the day(s) of the week. If absent, it indicates every day of the week.
        timeOfDayStart:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/TimeOfDay'
        timeOfDayEnd:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/TimeOfDay'
    CommunicationIndicator:
      anyOf:
      - type: string
        enum:
          - PERIODICALLY
          - ON_DEMAND
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration but is not used to encode
          content defined in the present version of this API.
      description: >
        Possible values are
        - PERIODICALLY: Identifies the UE communicates periodically
        - ON_DEMAND: Identifies the UE communicates on demand
    StationaryIndication:
      anyOf:
      - type: string
        enum:
          - STATIONARY
          - MOBILE
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration but is not used to encode
          content defined in the present version of this API.
      description: >
        Possible values are
        - STATIONARY: Identifies the UE is stationary
        - MOBILE: Identifies the UE is mobile
